version: '2'
services:
  roammeet-people-service:
    image: roammeet/elixir:latest
    container_name: roammeet-people-service
    ports:
      - "8008:8008"
    user: ${UID}
    volumes:
      - "../roammeet-people-service:/usr/src/people"
    command: bash -c "cd /usr/src/people && mix deps.get && mix run --no-halt"
  roammeet-meetup-service:
    image: roammeet/elixir:latest
    container_name: roammeet-meetup-service
    ports:
      - "8009:8009"
    user: ${UID}
    volumes:
      - "../roammeet-meetup-service:/usr/src/meetup"
    command: bash -c "cd /usr/src/meetup && mix deps.get && mix run --no-halt"
